---
title: "clases de R"
author: "Kelvin Llanos"
format: html
editor_options: 
  chunk_output_type: console
---

# Disenos experimentales

## DCA: diseno completamente al azar

Dosis de fertilizacion nitrogenada:

- 0
- 50
- 100
- 150

Rep: 5

```{r}
# Cargar la librería necesaria
library(agricolae)

# Definir los niveles de fertilización y el número de repeticiones
niveles_fertilizacion <- c(0, 50, 100, 150)
repeticiones <- 5

# Crear el diseño DCA
dca <- design.crd(trt = niveles_fertilizacion, r = repeticiones)

# Mostrar la estructura del diseño
print(dca)

# Si quieres ver cómo quedarían los tratamientos en cada bloque
as.data.frame(dca$design)






```

## DBCA

Factor 1 (dosis nitrogeno): 0, 50, 100, 150
Factor 2 (variedades de papa): canchan y peruanita
Bloques: 5
```{r}
# factorial 4 x 2 con 3 bloques
library(agricolae)
trt <- c(4,2) # factorial 4x2

dosis <- c(0, 50, 100, 150)
variedad <- c("canchan", "peruanita")

outdesign <- design.ab(trt = trt, r=5)

str(outdesign)
book <- outdesign$book

book
```

# title: "Potato"
author: "Kelvin Llanos"
format: html
editor_options: 
  chunk_output_type: console
  
```{r}
library(readxl)
fb<- read_excel("LA MOLINA 2014 POTATO WUE (FB).xlsx", 
    sheet = "fb", col_types = c("text", "text", 
        "text", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))
View(fb)
str(fb)

```



# Analisis de datos

```{r}
library(tidyverse)
library(googlesheets4)
```

## Importar datos

```{r}
#url <- ""
  
  #gs <- as_sheets_id(url)
#fb <- range_read(gs,"fb")
#str(fb)
```

## Modelo estadistico

```{r}
modelo <- aov(formula = lfa ~ bloque + riego*geno, data = fb)

anova(modelo)

plot(modelo)

```

## Comparacion de medias 

```{r}

library(agricolae)
mc <- agricolae::duncan.test(y = modelo,trt = c("riego","geno"))

mc

str(mc)
```


```{r}

library(emmeans)
library(multcomp)
library(tidyverse)
library(inti)

mc <- emmeans(modelo, ~ riego | geno)
mc_cld <- mc %>%
  cld(Letters = letters, reversed = TRUE)

mc_cld
```

## Grafico

```{r}
library(inti)

plot_smr(data = mc_cld
         , type = "bar"
         , x = "geno"
         , y = "emmean"
         , group = "riego"
         , sig = ".group"
         , error = "SE"
         , ylimits = c(0, 12000, 2000))
```

```{r}
ggplot(mc_cld, aes(x = geno, y = emmean, fi11 = riego)) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Grafico de barras", x = "Categoria", y = "valores")
```


